### ISSUE TITLE
iPad Support?

### ISSUE THREAD

**Issue by Puddinglord** [Oromis/touch-vtt#2]
This isn't really your issue. I was wondering if you have an iPad to test this with? In 0.7.7 I am unable to log in to a user to get to the map. 

I would love to track down this issue.

**Comment by Oromis** [comment]
I just tried it with my iPad Air 2 and I couldn't log in either - but that's true whether TouchVTT is enabled or not, so it's not a TouchVTT issue. 

It doesn't work either on my iPhone running iOS 14.2.

Unfortunately Safari lags behind Chromium and Firefox by a long way in terms of standard compliance so I guess Foundry may use one of these features that aren't supported by Safari. But that's just my guess.

Since this is a core Foundry issue and not a problem of TouchVTT, I'll close this. Please raise this issue with the Foundry team.
