### ISSUE TITLE
Request - Split Zoom and Pan gestures

### ISSUE THREAD

**Issue by Deuterazamus** [Oromis/touch-vtt#3]
Zooming and panning with 2 fingers is kinda wonky. While zooming the map tends to move around and while panning the zoom is ever so slighty adjusted continuously.

Possibly assigning 2 touch points for zoom and 3 for pan could improve usability.

**Comment by Oromis** [comment]
Yeah, I'm aware of that. I'll try to get zooming and panning to be more stable.

Having said that, your suggestion is quite interesting and could have some value. I'll probably implement it when I find the time (probably not before the weekend)

**Comment by CCRPG** [comment]
I would very much appreciate it if you looked into the topic. I play in IRL and we used Roll20 with infrared touchscreen TV. However, my players have small trouble with moving tokens (I guess it's a slightly different movement than in Roll20 touch implementation) but the real issue is with zooming/panning the camera. Having significantly different gestures or perhaps some other solution would really help, especially since we use less precise infrared technology. 

Best Regards

**Comment by Oromis** [comment]
Due to popular demand, this is implemented in version 1.3.0 of Touch VTT :)
