### ISSUE TITLE
Alternate usage?

### ISSUE THREAD

**Issue by ghostphoenix713** [Oromis/touch-vtt#99]
I have one person in my group that uses a tablet and the rest are on PC. Is there a way to set this module for that person only and not the rest of us? I know some modules can be set by the individual vs the whole group, so I wanted to check.

**Comment by Aioros** [comment]
Hey, yes, that's doable, but I'll admit it's not super convenient. Basically everybody who doesn't need the module would go in TouchVTT's settings and uncheck the "Core Functionality" one.

Let me know if you have any issues with that. I'll leave this issue open because I might take the opportunity to implement a better way to do that.

**Comment by Aioros** [comment]
Sorry, forgot to mention: in theory, TouchVTT should have minimal impact on functionality for anyone with a mouse already. If your pc players are having issues with it, I'd like to know so I can try to avoid them.
